# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Build and Test TCK sigtest Tooling

on:
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/sigtest-ci.yml'
      - 'tools/sigtest/**'
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/sigtest-ci.yml'
      - 'tools/sigtest/**'

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-sigtest-tools:

    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        java: ['17', '21', '23']

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: sigtest-jdk-${{ matrix.java }}
        run:  |
          cd tools/sigtest
          mvn clean install -U -B -fae
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports-jdk-${{ matrix.java }}
          path: '**/surefire-reports/'
